--
-- PostgreSQL database dump
--

-- Dumped from database version 15.7 (Homebrew)
-- Dumped by pg_dump version 15.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: student; Type: TABLE; Schema: public; Owner: lisalin
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    age integer NOT NULL,
    grade character varying(255),
    name character varying(255)
);


ALTER TABLE public.student OWNER TO lisalin;

--
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: lisalin
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: lisalin
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    name character varying(255),
    age integer,
    grade character varying(255),
    password character varying(255)
);


ALTER TABLE public.students OWNER TO lisalin;

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: lisalin
--

CREATE SEQUENCE public.students_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.students_id_seq OWNER TO lisalin;

--
-- Name: students_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: lisalin
--

ALTER SEQUENCE public.students_id_seq OWNED BY public.students.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: lisalin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO lisalin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: lisalin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students id; Type: DEFAULT; Schema: public; Owner: lisalin
--

ALTER TABLE ONLY public.students ALTER COLUMN id SET DEFAULT nextval('public.students_id_seq'::regclass);


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: lisalin
--

COPY public.student (id, age, grade, name) FROM stdin;
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: lisalin
--

COPY public.students (id, name, age, grade, password) FROM stdin;
2	Jane Smith	21	B	123456
3	Alice Johnson	23	A	123456
5	Emma Johnson	12	A	123456
6	Liam Thompson	21	B	123456
7	Olivia Martinez	23	A	123456
4	Emily Carter	13	A	123456
9	Lisalinin	0	\N	123456
10	qwe	0	\N	123456
11	wewrwe	0	\N	123456
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: lisalin
--

COPY public.users (id, password, username) FROM stdin;
\.


--
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lisalin
--

SELECT pg_catalog.setval('public.student_id_seq', 1, false);


--
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lisalin
--

SELECT pg_catalog.setval('public.students_id_seq', 11, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lisalin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: lisalin
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: lisalin
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: lisalin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: lisalin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

